version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      - run:
          name: Setup NPM Token
          command: |
            npm config set registry "https://registry.npmjs.org/"
            echo "@hungphongbk:registry=https://npm.pkg.github.com" > .npmrc

      # https://github.com/atlassian/react-beautiful-dnd/issues/1007#issuecomment-446415426
      - run:
          name: Workaround for Flow crashing
          command: echo "server.max_workers=1" >> .flowconfig

      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: build
          command: npm run prepublishOnly
      - run:
          name: release
          command: npm run semantic-release
